// Modal action type
export const SHOW_OR_HIDE_ERROR_MODAL = "SHOW_OR_HIDE_ERROR_MODAL";
export const SHOW_OR_HIDE_DEDUCT_CONFIRMATION_MODAL =
  "SHOW_OR_HIDE_DEDUCT_CONFIRMATION_MODAL";

// Loader action types
export const SHOW_API_LOADER = "SHOW_API_LOADER";
export const HIDE_API_LOADER = "HIDE_API_LOADER";

// Toast action types
export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";

// Authloading action types
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_FCM_TOKEN = "SET_FCM_TOKEN";
export const SET_APP_STATE = "SET_APP_STATE";
export const SET_APP_SCREEN = "SET_APP_SCREEN";

// Forgot Password Types
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const RESET_FORGOT_PASSWORD_STATE = "RESET_FORGOT_PASSWORD_STATE";

// Sigup Types
export const CREATE_USER = "CREATE_USER";
export const UPLOAD_USER_DETAIL_DATA = "UPLOAD_USER_DETAIL_DATA";

// Login Types
export const LOGIN_FIREBASE_USER = "LOGIN_FIREBASE_USER";
export const LOGIN_FIREBASE_API_HIT_FAILURE = "LOGIN_FIREBASE_API_HIT_FAILURE";
export const RESET_LOGIN_STATE = "RESET_LOGIN_STATE";

// Account Types
export const SIGN_OUT_API_HIT = "SIGN_OUT_API_HIT";

// Ask Types
export const CLEAR_ASK_STATE = "CLEAR_ASK_STATE";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const GET_QUESTION_DATA = "GET_QUESTION_DATA";
export const GET_QUESTION_DATA_SUCCESS = "GET_QUESTION_DATA_SUCCESS";
export const GET_RECENT_EXPERTS_DATA_SUCCESS =
  "GET_RECENT_EXPERTS_DATA_SUCCESS";
export const GET_PREVIOUS_QUESTION_DATA_SUCCESS =
  "GET_PREVIOUS_QUESTION_DATA_SUCCESS";
export const CLEAR_QUESTION_VALUE = "CLEAR_QUESTION_VALUE";
export const GET_EXPERT_QUESTION_DATA = "GET_EXPERT_QUESTION_DATA";
export const GET_EXPERT_QUESTION_SUCCESS = "GET_EXPERT_QUESTION_SUCCESS";
export const GET_EXPERT_RESOLVED_QUESTION_SUCCESS =
  "GET_EXPERT_RESOLVED_QUESTION_SUCCESS";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";

// Expert Profile Types
export const GET_EXPERTS_DETAIL_DATA = "GET_EXPERTS_DETAIL_DATA";
export const GET_EXPERTS_DETAIL_DATA_SUCCESS =
  "GET_EXPERTS_DETAIL_DATA_SUCCESS";
export const CLEAR_EXPERT_PROFILE_STATE = "CLEAR_EXPERT_PROFILE_STATE";

// Expert Profile Types
export const GET_EXPERTS_DATA = "GET_EXPERTS_DATA";
export const GET_EXPERTS_DATA_SUCCESS = "GET_EXPERTS_DATA_SUCCESS";
export const CLEAR_CHOOSE_EXPERT_STATE = "CLEAR_CHOOSE_EXPERT_STATE";
export const GET_PROFESSIONS_DATA_SUCCESS = "GET_PROFESSIONS_DATA_SUCCESS";
export const GET_LANGUAGES_DATA_SUCCESS = "GET_LANGUAGES_DATA_SUCCESS";

// Change Password Types
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

// Setting Screen Types
export const UPDATE_USER_DETAIL_DATA = "UPDATE_USER_DETAIL_DATA";
export const UPDATE_EXPERT_DETAIL_DATA = "UPDATE_EXPERT_DETAIL_DATA";

// Chat Types
export const CHAT_MESSAGE_LOADING = "CHAT_MESSAGE_LOADING";
export const CHAT_MESSAGE_SUCCESS = "CHAT_MESSAGE_SUCCESS";
export const CHAT_MESSAGE_ERROR = "CHAT_MESSAGE_ERROR";
export const CHAT_MESSAGE_UPDATE = "CHAT_MESSAGE_UPDATE";
export const CHAT_LOAD_MESSAGES_SUCCESS = "CHAT_LOAD_MESSAGES_SUCCESS";
export const CHAT_MESSAGE_SENDING = "CHAT_MESSAGE_SENDING";
export const CHAT_IMAGE_UPLOAD = "CHAT_IMAGE_UPLOAD";
export const CHAT_LOAD_MESSAGES_ERROR = "CHAT_LOAD_MESSAGES_ERROR";
export const SET_QUESTION = "SET_QUESTION";
export const CLEAR_CHAT_STATE = "CLEAR_CHAT_STATE";
export const SET_QUESTION_ID = "SET_QUESTION_ID";
export const SET_EXPERT_RATING = "SET_EXPERT_RATING";
export const CHECK_EXPERT_STATUS = "CHECK_EXPERT_STATUS";
export const CHECK_EXPERT_STATUS_SUCCESS = "CHECK_EXPERT_STATUS_SUCCESS";
export const CHECK_QUESTION_STATUS_SUCCESS = "CHECK_QUESTION_STATUS_SUCCESS";
export const TOGGLE_USER_STATUS = "TOGGLE_USER_STATUS";
export const STOP_OBSERVER_CHAT = "STOP_OBSERVER_CHAT";

export const CHAT_MESSAGE_EXPERT_LOADING = "CHAT_MESSAGE_EXPERT_LOADING";
export const CHAT_LOAD_MESSAGES_EXPERT_SUCCESS =
  "CHAT_LOAD_MESSAGES_EXPERT_SUCCESS";
export const CHAT_LOAD_MESSAGES_EXPERT_ERROR =
  "CHAT_LOAD_MESSAGES_EXPERT_ERROR";
export const CHAT_IMAGE_EXPERT_UPLOAD = "CHAT_IMAGE_EXPERT_UPLOAD";
export const CLEAR_CHAT_EXPERT_STATE = "CLEAR_CHAT_EXPERT_STATE";
export const CHAT_MESSAGE_EXPERT_SUCCESS = "CHAT_MESSAGE_EXPERT_SUCCESS";
export const CHAT_MESSAGE_EXPERT_ERROR = "CHAT_MESSAGE_EXPERT_ERROR";
export const SET_QUESTION_EXPERT_DATA = "SET_QUESTION_EXPERT_DATA";
export const CHAT_MESSAGE_EXPERT_SENDING = "CHAT_MESSAGE_EXPERT_SENDING";
export const CHECK_QUESTION_EXPERT_STATUS_SUCCESS =
  "CHECK_QUESTION_EXPERT_STATUS_SUCCESS";
export const CHECK_USER_STATUS = "CHECK_USER_STATUS";
export const CHECK_USER_STATUS_SUCCESS = "CHECK_USER_STATUS_SUCCESS";
export const TOGGLE_EXPERT_STATUS = "TOGGLE_EXPERT_STATUS";
export const RESOLVE_QUESTION = "RESOLVE_QUESTION";

export const CREATE_PAYMENT_CARD = "CREATE_PAYMENT_CARD";
export const GET_CREDIT_AMOUNT_OPTIONS = "GET_CREDIT_AMOUNT_OPTIONS";
export const SET_CREDIT_AMOUNT_OPTIONS = "SET_CREDIT_AMOUNT_OPTIONS";
export const GET_PAYMENT_METHODS = "GET_PAYMENT_METHODS";
export const SET_PAYMENT_METHODS = "SET_PAYMENT_METHODS";
export const BUY_CREDITS_WITH_CARD = "BUY_CREDITS_WITH_CARD";
export const BUY_CREDITS_WITH_TOKEN = "BUY_CREDITS_WITH_TOKEN";
export const BUY_CREDITS_WITH_PAYPAL = "BUY_CREDITS_WITH_PAYPAL";
export const SET_ORDER_DATA = "SET_ORDER_DATA";
export const CAPTURE_PAYMENT = "CAPTURE_PAYMENT";
export const SET_NATIVE_PAY_SUPPORT = "SET_NATIVE_PAY_SUPPORT";

// Health History Types
export const UPDATE_BASIC_INFO = "UPDATE_BASIC_INFO";
export const UPDATE_PREGNANCY_HISTORY = "UPDATE_PREGNANCY_HISTORY";
export const UPDATE_LIFESTYLE = "UPDATE_LIFESTYLE";
export const UPDATE_ALLERGIES = "UPDATE_ALLERGIES";
export const UPDATE_MEDICATIONS = "UPDATE_MEDICATIONS";
export const UPDATE_MEDICAL_HISTORY = "UPDATE_MEDICAL_HISTORY";
export const UPDATE_INSURANCE = "UPDATE_INSURANCE";
